
// Generated by Cadence Genus(TM) Synthesis Solution 17.24-s038_1
// Generated on: Jul 24 2023 20:30:58 IST (Jul 24 2023 15:00:58 UTC)

// Verification Directory fv/comparator 

module comparator(a, b, g, e, l);
  input [0:3] a, b;
  output g, e, l;
  wire [0:3] a, b;
  wire g, e, l;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19;
  nr02d0 g438(.A1 (e), .A2 (g), .ZN (l));
  nr02d0 g439(.A1 (n_19), .A2 (n_9), .ZN (g));
  nr02d0 g441(.A1 (n_17), .A2 (n_18), .ZN (n_19));
  nr03d0 g440(.A1 (n_18), .A2 (n_12), .A3 (n_16), .ZN (e));
  nr02d0 g442(.A1 (n_15), .A2 (n_8), .ZN (n_17));
  nd03d0 g443(.A1 (n_11), .A2 (n_14), .A3 (n_10), .ZN (n_16));
  an02d0 g444(.A1 (n_13), .A2 (n_14), .Z (n_15));
  nd02d0 g445(.A1 (n_12), .A2 (n_11), .ZN (n_13));
  nr03d0 g446(.A1 (n_5), .A2 (n_9), .A3 (n_8), .ZN (n_10));
  nd02d0 g447(.A1 (n_7), .A2 (n_6), .ZN (n_12));
  nd02d0 g449(.A1 (n_4), .A2 (a[3]), .ZN (n_7));
  nd02d0 g448(.A1 (n_0), .A2 (a[2]), .ZN (n_6));
  nr02d0 g450(.A1 (n_2), .A2 (a[0]), .ZN (n_9));
  nd02d0 g454(.A1 (n_1), .A2 (b[2]), .ZN (n_11));
  nr02d0 g452(.A1 (n_4), .A2 (a[3]), .ZN (n_5));
  nd02d0 g453(.A1 (n_3), .A2 (a[1]), .ZN (n_14));
  nr02d0 g451(.A1 (n_3), .A2 (a[1]), .ZN (n_8));
  an02d0 g455(.A1 (n_2), .A2 (a[0]), .Z (n_18));
  inv0d0 g459(.I (a[2]), .ZN (n_1));
  inv0d0 g458(.I (b[3]), .ZN (n_4));
  inv0d0 g460(.I (b[2]), .ZN (n_0));
  inv0d0 g457(.I (b[1]), .ZN (n_3));
  inv0d0 g456(.I (b[0]), .ZN (n_2));
endmodule

