
// Generated by Cadence Genus(TM) Synthesis Solution 17.24-s038_1
// Generated on: Jul 24 2023 20:42:53 IST (Jul 24 2023 15:12:53 UTC)

// Verification Directory fv/comparator 

module comparator(a, b, g, e, l);
  input [0:3] a, b;
  output g, e, l;
  wire [0:3] a, b;
  wire g, e, l;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_38, n_39, n_40;
  wire n_42;
  an02d0 g438(.A1 (n_42), .A2 (n_38), .Z (l));
  inv0d0 g439(.I (g), .ZN (n_42));
  an02d0 g440(.A1 (n_40), .A2 (n_19), .Z (g));
  inv0d0 g443(.I (n_39), .ZN (n_40));
  an02d0 g444(.A1 (n_35), .A2 (n_36), .Z (n_39));
  inv0d0 g441(.I (e), .ZN (n_38));
  an02d0 g442(.A1 (n_33), .A2 (n_36), .Z (e));
  inv0d0 g446(.I (n_34), .ZN (n_35));
  an02d0 g447(.A1 (n_32), .A2 (n_23), .Z (n_34));
  an02d0 g445(.A1 (n_31), .A2 (n_21), .Z (n_33));
  inv0d0 g449(.I (n_30), .ZN (n_32));
  an02d0 g448(.A1 (n_27), .A2 (n_29), .Z (n_31));
  an02d0 g450(.A1 (n_28), .A2 (n_29), .Z (n_30));
  inv0d0 g452(.I (n_26), .ZN (n_28));
  an02d0 g451(.A1 (n_24), .A2 (n_25), .Z (n_27));
  an02d0 g453(.A1 (n_22), .A2 (n_25), .Z (n_26));
  an02d0 g454(.A1 (n_20), .A2 (n_23), .Z (n_24));
  inv0d0 g455(.I (n_21), .ZN (n_22));
  an02d0 g456(.A1 (n_17), .A2 (n_18), .Z (n_21));
  an02d0 g457(.A1 (n_19), .A2 (n_16), .Z (n_20));
  inv0d0 g458(.I (n_9), .ZN (n_18));
  inv0d0 g468(.I (n_15), .ZN (n_25));
  inv0d0 g467(.I (n_14), .ZN (n_29));
  inv0d0 g469(.I (n_12), .ZN (n_36));
  inv0d0 g459(.I (n_10), .ZN (n_17));
  inv0d0 g466(.I (n_13), .ZN (n_16));
  inv0d0 g461(.I (n_8), .ZN (n_23));
  inv0d0 g460(.I (n_11), .ZN (n_19));
  an02d0 g472(.A1 (n_7), .A2 (b[2]), .Z (n_15));
  an02d0 g471(.A1 (n_3), .A2 (a[1]), .Z (n_14));
  an02d0 g470(.A1 (n_4), .A2 (b[3]), .Z (n_13));
  an02d0 g473(.A1 (n_5), .A2 (a[0]), .Z (n_12));
  an02d0 g464(.A1 (n_6), .A2 (b[0]), .Z (n_11));
  an02d0 g463(.A1 (n_0), .A2 (a[3]), .Z (n_10));
  an02d0 g462(.A1 (n_2), .A2 (a[2]), .Z (n_9));
  an02d0 g465(.A1 (n_1), .A2 (b[1]), .Z (n_8));
  inv0d0 g480(.I (a[2]), .ZN (n_7));
  inv0d0 g479(.I (a[0]), .ZN (n_6));
  inv0d0 g474(.I (b[0]), .ZN (n_5));
  inv0d0 g478(.I (a[3]), .ZN (n_4));
  inv0d0 g475(.I (b[1]), .ZN (n_3));
  inv0d0 g481(.I (b[2]), .ZN (n_2));
  inv0d0 g476(.I (a[1]), .ZN (n_1));
  inv0d0 g477(.I (b[3]), .ZN (n_0));
endmodule

