
// Generated by Cadence Genus(TM) Synthesis Solution 17.24-s038_1
// Generated on: Jul 14 2023 14:41:23 IST (Jul 14 2023 09:11:23 UTC)

// Verification Directory fv/csa 

module csa_tree_add_12_30_group_2(in_0, in_1, in_2, out_0);
  input [7:0] in_0, in_1, in_2;
  output [8:0] out_0;
  wire [7:0] in_0, in_1, in_2;
  wire [8:0] out_0;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_56, n_57;
  wire n_59, n_61, n_62, n_64, n_65, n_67, n_68, n_70;
  wire n_71, n_73;
  xr02d1 g371(.A1 (n_73), .A2 (n_30), .Z (out_0[8]));
  nd02d0 g372(.A1 (n_71), .A2 (n_51), .ZN (n_73));
  xr03d1 g373(.A1 (n_70), .A2 (n_38), .A3 (n_29), .Z (out_0[7]));
  nd02d0 g374(.A1 (n_70), .A2 (n_45), .ZN (n_71));
  nd02d0 g375(.A1 (n_68), .A2 (n_42), .ZN (n_70));
  xr03d1 g376(.A1 (n_67), .A2 (n_37), .A3 (n_27), .Z (out_0[6]));
  nd02d0 g377(.A1 (n_67), .A2 (n_52), .ZN (n_68));
  nd02d0 g378(.A1 (n_65), .A2 (n_50), .ZN (n_67));
  xr03d1 g379(.A1 (n_64), .A2 (n_33), .A3 (n_32), .Z (out_0[5]));
  nd02d0 g380(.A1 (n_64), .A2 (n_41), .ZN (n_65));
  nd02d0 g381(.A1 (n_62), .A2 (n_46), .ZN (n_64));
  xr03d1 g382(.A1 (n_61), .A2 (n_39), .A3 (n_24), .Z (out_0[4]));
  nd02d0 g383(.A1 (n_61), .A2 (n_43), .ZN (n_62));
  nd02d0 g384(.A1 (n_59), .A2 (n_53), .ZN (n_61));
  xr03d1 g385(.A1 (n_57), .A2 (n_35), .A3 (n_31), .Z (out_0[3]));
  nd02d0 g386(.A1 (n_57), .A2 (n_49), .ZN (n_59));
  xr03d1 g387(.A1 (n_48), .A2 (n_34), .A3 (n_7), .Z (out_0[2]));
  nd02d0 g388(.A1 (n_56), .A2 (n_54), .ZN (n_57));
  nd02d0 g389(.A1 (n_47), .A2 (n_44), .ZN (n_56));
  xr03d1 g390(.A1 (n_28), .A2 (n_16), .A3 (in_1[1]), .Z (out_0[1]));
  nd02d0 g391(.A1 (n_34), .A2 (n_8), .ZN (n_54));
  nd02d0 g392(.A1 (n_35), .A2 (n_31), .ZN (n_53));
  or02d0 g393(.A1 (n_37), .A2 (n_27), .Z (n_52));
  nd02d0 g394(.A1 (n_38), .A2 (n_29), .ZN (n_51));
  nd02d0 g395(.A1 (n_33), .A2 (n_32), .ZN (n_50));
  or02d0 g396(.A1 (n_35), .A2 (n_31), .Z (n_49));
  inv0d0 g397(.I (n_47), .ZN (n_48));
  nd02d0 g398(.A1 (n_39), .A2 (n_24), .ZN (n_46));
  or02d0 g399(.A1 (n_38), .A2 (n_29), .Z (n_45));
  or02d0 g400(.A1 (n_34), .A2 (n_8), .Z (n_44));
  or02d0 g401(.A1 (n_39), .A2 (n_24), .Z (n_43));
  nd02d0 g402(.A1 (n_37), .A2 (n_27), .ZN (n_42));
  or02d0 g403(.A1 (n_33), .A2 (n_32), .Z (n_41));
  nd02d0 g404(.A1 (n_40), .A2 (n_26), .ZN (n_47));
  nd02d0 g405(.A1 (n_25), .A2 (n_28), .ZN (n_40));
  xr03d1 g406(.A1 (in_2[4]), .A2 (in_0[4]), .A3 (in_1[4]), .Z (n_39));
  xr03d1 g407(.A1 (in_2[7]), .A2 (in_0[7]), .A3 (in_1[7]), .Z (n_38));
  xr03d1 g408(.A1 (in_2[6]), .A2 (in_0[6]), .A3 (in_1[6]), .Z (n_37));
  xr03d1 g409(.A1 (in_0[0]), .A2 (in_1[0]), .A3 (in_2[0]), .Z
       (out_0[0]));
  xr03d1 g410(.A1 (in_2[3]), .A2 (in_0[3]), .A3 (in_1[3]), .Z (n_35));
  xr03d1 g411(.A1 (in_2[2]), .A2 (in_0[2]), .A3 (in_1[2]), .Z (n_34));
  xr03d1 g412(.A1 (in_2[5]), .A2 (in_0[5]), .A3 (in_1[5]), .Z (n_33));
  nd02d0 g413(.A1 (n_18), .A2 (n_0), .ZN (n_32));
  nd02d0 g414(.A1 (n_19), .A2 (n_3), .ZN (n_31));
  nd02d0 g415(.A1 (n_17), .A2 (n_13), .ZN (n_30));
  nd02d0 g416(.A1 (n_22), .A2 (n_2), .ZN (n_29));
  nd02d0 g417(.A1 (n_20), .A2 (n_5), .ZN (n_28));
  nd02d0 g418(.A1 (n_21), .A2 (n_6), .ZN (n_27));
  nd02d0 g419(.A1 (n_16), .A2 (in_1[1]), .ZN (n_26));
  or02d0 g420(.A1 (n_16), .A2 (in_1[1]), .Z (n_25));
  nd02d0 g421(.A1 (n_23), .A2 (n_14), .ZN (n_24));
  nd02d0 g422(.A1 (n_11), .A2 (in_2[3]), .ZN (n_23));
  nd02d0 g423(.A1 (n_15), .A2 (in_2[6]), .ZN (n_22));
  nd02d0 g424(.A1 (n_9), .A2 (in_2[5]), .ZN (n_21));
  nd02d0 g425(.A1 (n_12), .A2 (in_2[0]), .ZN (n_20));
  nd02d0 g426(.A1 (n_1), .A2 (in_2[2]), .ZN (n_19));
  nd02d0 g427(.A1 (n_10), .A2 (in_2[4]), .ZN (n_18));
  nd02d0 g428(.A1 (n_4), .A2 (in_2[7]), .ZN (n_17));
  xr02d1 g429(.A1 (in_0[1]), .A2 (in_2[1]), .Z (n_16));
  or02d0 g430(.A1 (in_0[6]), .A2 (in_1[6]), .Z (n_15));
  nd02d0 g431(.A1 (in_0[3]), .A2 (in_1[3]), .ZN (n_14));
  nd02d0 g432(.A1 (in_0[7]), .A2 (in_1[7]), .ZN (n_13));
  or02d0 g433(.A1 (in_0[0]), .A2 (in_1[0]), .Z (n_12));
  or02d0 g434(.A1 (in_0[3]), .A2 (in_1[3]), .Z (n_11));
  or02d0 g435(.A1 (in_0[4]), .A2 (in_1[4]), .Z (n_10));
  or02d0 g436(.A1 (in_0[5]), .A2 (in_1[5]), .Z (n_9));
  inv0d0 g437(.I (n_7), .ZN (n_8));
  nd02d0 g438(.A1 (in_0[5]), .A2 (in_1[5]), .ZN (n_6));
  nd02d0 g439(.A1 (in_0[0]), .A2 (in_1[0]), .ZN (n_5));
  or02d0 g440(.A1 (in_0[7]), .A2 (in_1[7]), .Z (n_4));
  nd02d0 g441(.A1 (in_0[2]), .A2 (in_1[2]), .ZN (n_3));
  nd02d0 g442(.A1 (in_0[6]), .A2 (in_1[6]), .ZN (n_2));
  or02d0 g443(.A1 (in_0[2]), .A2 (in_1[2]), .Z (n_1));
  nd02d0 g444(.A1 (in_0[4]), .A2 (in_1[4]), .ZN (n_0));
  nd02d0 g445(.A1 (in_0[1]), .A2 (in_2[1]), .ZN (n_7));
endmodule

module csa(a, b, c_in, sum);
  input [7:0] a, b, c_in;
  output [8:0] sum;
  wire [7:0] a, b, c_in;
  wire [8:0] sum;
  wire [8:0] carry_out;
  wire [8:0] partial_sum;
  wire n_0, n_1;
  assign sum[0] = partial_sum[0];
  assign sum[1] = partial_sum[1];
  assign sum[2] = partial_sum[2];
  assign sum[3] = partial_sum[3];
  assign sum[4] = partial_sum[4];
  assign sum[5] = partial_sum[5];
  assign sum[6] = partial_sum[6];
  assign sum[7] = partial_sum[7];
  assign sum[8] = carry_out[8];
  csa_tree_add_12_30_group_2 csa_tree_add_12_30_groupi(.in_0 (c_in),
       .in_1 (a), .in_2 (b), .out_0 (partial_sum));
  nr02d0 g31(.A1 (n_0), .A2 (n_1), .ZN (carry_out[8]));
  nr02d0 g32(.A1 (partial_sum[7]), .A2 (partial_sum[6]), .ZN (n_1));
  inv0d0 g33(.I (partial_sum[8]), .ZN (n_0));
endmodule

