
// Generated by Cadence Genus(TM) Synthesis Solution 17.24-s038_1
// Generated on: Jul 27 2023 01:35:36 IST (Jul 26 2023 20:05:36 UTC)

// Verification Directory fv/keccak_sbox 

module keccak_sbox(x, y);
  input [4:0] x;
  output [4:0] y;
  wire [4:0] x;
  wire [4:0] y;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_13, n_16, n_17;
  xr02d1 g230(.A1 (n_17), .A2 (n_6), .Z (y[1]));
  xr02d1 g234(.A1 (n_16), .A2 (n_9), .Z (y[2]));
  xr02d1 g232(.A1 (n_16), .A2 (x[1]), .Z (n_17));
  xr02d1 g231(.A1 (n_13), .A2 (n_11), .Z (y[4]));
  xr02d1 g233(.A1 (n_13), .A2 (n_10), .Z (y[0]));
  xr02d1 g237(.A1 (n_8), .A2 (n_4), .Z (n_16));
  xr02d1 g236(.A1 (n_11), .A2 (n_10), .Z (y[3]));
  xr02d1 g235(.A1 (n_9), .A2 (n_0), .Z (n_13));
  nd02d0 g238(.A1 (n_7), .A2 (x[4]), .ZN (n_8));
  nr02d0 g241(.A1 (n_3), .A2 (n_1), .ZN (n_7));
  nd02d0 g239(.A1 (n_5), .A2 (x[3]), .ZN (n_9));
  xr02d1 g240(.A1 (x[2]), .A2 (n_2), .Z (n_11));
  inv0d0 g243(.I (n_10), .ZN (n_6));
  xr02d1 g242(.A1 (x[4]), .A2 (x[0]), .Z (n_5));
  xr02d1 g244(.A1 (x[4]), .A2 (x[2]), .Z (n_4));
  inv0d0 g247(.I (n_2), .ZN (n_3));
  xr02d1 g245(.A1 (x[3]), .A2 (x[0]), .Z (n_10));
  nd02d0 g248(.A1 (x[1]), .A2 (x[0]), .ZN (n_2));
  nr02d0 g246(.A1 (x[1]), .A2 (x[0]), .ZN (n_1));
  inv0d0 g249(.I (x[1]), .ZN (n_0));
endmodule

