
// Generated by Cadence Genus(TM) Synthesis Solution 17.24-s038_1
// Generated on: Jul 14 2023 14:31:17 IST (Jul 14 2023 09:01:17 UTC)

// Verification Directory fv/maxpool 

module maxpool(in1, in2, max_out);
  input [7:0] in1, in2;
  output [7:0] max_out;
  wire [7:0] in1, in2;
  wire [7:0] max_out;
  wire n_0, n_1, n_2, n_3, n_4, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54;
  nd02d0 g615(.A1 (n_49), .A2 (n_42), .ZN (max_out[6]));
  nd02d0 g617(.A1 (n_48), .A2 (n_39), .ZN (max_out[5]));
  nd02d0 g620(.A1 (n_51), .A2 (n_46), .ZN (max_out[4]));
  nd02d0 g621(.A1 (n_53), .A2 (n_43), .ZN (max_out[1]));
  nd02d0 g618(.A1 (n_47), .A2 (n_41), .ZN (max_out[2]));
  nd02d0 g619(.A1 (n_50), .A2 (n_45), .ZN (max_out[3]));
  nd02d0 g616(.A1 (n_54), .A2 (n_40), .ZN (max_out[0]));
  nd02d0 g626(.A1 (n_52), .A2 (in1[0]), .ZN (n_54));
  nd02d0 g624(.A1 (n_52), .A2 (in1[1]), .ZN (n_53));
  nd02d0 g631(.A1 (n_52), .A2 (in1[4]), .ZN (n_51));
  nd02d0 g633(.A1 (n_52), .A2 (in1[3]), .ZN (n_50));
  nd02d0 g627(.A1 (n_52), .A2 (in1[6]), .ZN (n_49));
  nd02d0 g622(.A1 (n_52), .A2 (in1[5]), .ZN (n_48));
  nd02d0 g629(.A1 (n_52), .A2 (in1[2]), .ZN (n_47));
  nd02d0 g630(.A1 (n_44), .A2 (in2[4]), .ZN (n_46));
  nd02d0 g632(.A1 (n_44), .A2 (in2[3]), .ZN (n_45));
  nd02d0 g623(.A1 (n_44), .A2 (in2[1]), .ZN (n_43));
  nd02d0 g628(.A1 (n_44), .A2 (in2[6]), .ZN (n_42));
  nd02d0 g634(.A1 (n_44), .A2 (in2[2]), .ZN (n_41));
  nd02d0 g625(.A1 (n_44), .A2 (in2[0]), .ZN (n_40));
  nd02d0 g635(.A1 (n_44), .A2 (in2[5]), .ZN (n_39));
  inv0d0 g636(.I (n_44), .ZN (n_52));
  nd02d0 g637(.A1 (n_38), .A2 (n_27), .ZN (n_44));
  an02d0 g638(.A1 (n_37), .A2 (n_12), .Z (n_38));
  nd02d0 g639(.A1 (n_36), .A2 (n_18), .ZN (n_37));
  nd02d0 g640(.A1 (n_35), .A2 (n_26), .ZN (n_36));
  nr02d0 g641(.A1 (n_34), .A2 (n_15), .ZN (n_35));
  nr02d0 g642(.A1 (n_33), .A2 (n_22), .ZN (n_34));
  nd02d0 g643(.A1 (n_32), .A2 (n_11), .ZN (n_33));
  nd02d0 g644(.A1 (n_31), .A2 (n_28), .ZN (n_32));
  nr02d0 g645(.A1 (n_30), .A2 (n_7), .ZN (n_31));
  nr02d0 g646(.A1 (n_29), .A2 (n_19), .ZN (n_30));
  nd02d0 g647(.A1 (n_25), .A2 (n_16), .ZN (n_29));
  nd02d0 g648(.A1 (n_20), .A2 (in2[2]), .ZN (n_28));
  nd02d0 g649(.A1 (n_24), .A2 (in2[6]), .ZN (n_27));
  nd02d0 g650(.A1 (n_23), .A2 (in2[4]), .ZN (n_26));
  nd02d0 g651(.A1 (n_21), .A2 (n_9), .ZN (n_25));
  nr02d0 g652(.A1 (n_17), .A2 (in1[6]), .ZN (n_24));
  nr02d0 g653(.A1 (n_22), .A2 (in1[4]), .ZN (n_23));
  nd02d0 g654(.A1 (n_14), .A2 (in2[0]), .ZN (n_21));
  nr02d0 g655(.A1 (n_19), .A2 (in1[2]), .ZN (n_20));
  nr02d0 g656(.A1 (n_17), .A2 (n_10), .ZN (n_18));
  nd02d0 g663(.A1 (n_3), .A2 (in1[2]), .ZN (n_16));
  an02d0 g666(.A1 (n_13), .A2 (in2[5]), .Z (n_15));
  or02d0 g664(.A1 (n_8), .A2 (in2[1]), .Z (n_14));
  nr02d0 g661(.A1 (n_13), .A2 (in2[5]), .ZN (n_22));
  nr02d0 g662(.A1 (n_4), .A2 (in2[3]), .ZN (n_19));
  nd02d0 g667(.A1 (n_6), .A2 (in2[7]), .ZN (n_12));
  nd02d0 g665(.A1 (n_0), .A2 (in1[4]), .ZN (n_11));
  nr02d0 g657(.A1 (n_1), .A2 (in2[6]), .ZN (n_10));
  nd02d0 g658(.A1 (n_8), .A2 (in2[1]), .ZN (n_9));
  nr02d0 g659(.A1 (n_2), .A2 (in1[3]), .ZN (n_7));
  nr02d0 g660(.A1 (n_6), .A2 (in2[7]), .ZN (n_17));
  or02d0 g668(.A1 (in1[7]), .A2 (in2[7]), .Z (max_out[7]));
  inv0d0 g672(.I (in1[3]), .ZN (n_4));
  inv0d0 g669(.I (in2[2]), .ZN (n_3));
  inv0d0 g674(.I (in2[3]), .ZN (n_2));
  inv0d0 g671(.I (in1[6]), .ZN (n_1));
  inv0d0 g676(.I (in2[4]), .ZN (n_0));
  inv0d0 g673(.I (in1[1]), .ZN (n_8));
  inv0d0 g670(.I (in1[5]), .ZN (n_13));
  inv0d0 g675(.I (in1[7]), .ZN (n_6));
endmodule

