
// Generated by Cadence Genus(TM) Synthesis Solution 17.24-s038_1
// Generated on: Jul 20 2023 21:44:30 IST (Jul 20 2023 16:14:30 UTC)

// Verification Directory fv/mux2to1 

module mux2to1(out, a, b, s);
  input [7:0] a, b;
  input s;
  output [7:0] out;
  wire [7:0] a, b;
  wire s;
  wire [7:0] out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16;
  nd02d0 g141(.A1 (n_11), .A2 (n_3), .ZN (out[5]));
  nd02d0 g142(.A1 (n_13), .A2 (n_1), .ZN (out[6]));
  nd02d0 g139(.A1 (n_15), .A2 (n_5), .ZN (out[7]));
  nd02d0 g138(.A1 (n_16), .A2 (n_7), .ZN (out[4]));
  nd02d0 g137(.A1 (n_12), .A2 (n_6), .ZN (out[1]));
  nd02d0 g144(.A1 (n_8), .A2 (n_0), .ZN (out[2]));
  nd02d0 g143(.A1 (n_9), .A2 (n_2), .ZN (out[3]));
  nd02d0 g140(.A1 (n_10), .A2 (n_4), .ZN (out[0]));
  nd02d0 g147(.A1 (n_14), .A2 (b[4]), .ZN (n_16));
  nd02d0 g149(.A1 (n_14), .A2 (b[7]), .ZN (n_15));
  nd02d0 g145(.A1 (n_14), .A2 (b[6]), .ZN (n_13));
  nd02d0 g146(.A1 (n_14), .A2 (b[1]), .ZN (n_12));
  nd02d0 g151(.A1 (n_14), .A2 (b[5]), .ZN (n_11));
  nd02d0 g148(.A1 (n_14), .A2 (b[0]), .ZN (n_10));
  nd02d0 g150(.A1 (n_14), .A2 (b[3]), .ZN (n_9));
  nd02d0 g152(.A1 (n_14), .A2 (b[2]), .ZN (n_8));
  nd02d0 g155(.A1 (a[4]), .A2 (s), .ZN (n_7));
  nd02d0 g154(.A1 (a[1]), .A2 (s), .ZN (n_6));
  nd02d0 g153(.A1 (a[7]), .A2 (s), .ZN (n_5));
  nd02d0 g156(.A1 (a[0]), .A2 (s), .ZN (n_4));
  nd02d0 g159(.A1 (a[5]), .A2 (s), .ZN (n_3));
  nd02d0 g158(.A1 (a[3]), .A2 (s), .ZN (n_2));
  nd02d0 g157(.A1 (a[6]), .A2 (s), .ZN (n_1));
  nd02d0 g160(.A1 (a[2]), .A2 (s), .ZN (n_0));
  inv0d0 g161(.I (s), .ZN (n_14));
endmodule

