
// Generated by Cadence Genus(TM) Synthesis Solution 17.24-s038_1
// Generated on: Jul 23 2023 13:31:53 IST (Jul 23 2023 08:01:53 UTC)

// Verification Directory fv/present_sbox 

module present_sbox(op, idat, key);
  input [3:0] idat, key;
  output [3:0] op;
  wire [3:0] idat, key;
  wire [3:0] op;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_46;
  xr02d1 g255(.A1 (n_46), .A2 (key[2]), .Z (op[2]));
  xr02d1 g256(.A1 (n_43), .A2 (key[0]), .Z (op[0]));
  xr02d1 g258(.A1 (n_42), .A2 (key[3]), .Z (op[3]));
  inv0d0 g259(.I (n_44), .ZN (n_46));
  xr02d1 g257(.A1 (n_39), .A2 (key[1]), .Z (op[1]));
  an02d0 g260(.A1 (n_40), .A2 (n_22), .Z (n_44));
  xr02d1 g261(.A1 (n_38), .A2 (n_28), .Z (n_43));
  inv0d0 g263(.I (n_41), .ZN (n_42));
  an02d0 g264(.A1 (n_36), .A2 (n_24), .Z (n_41));
  an02d0 g262(.A1 (n_37), .A2 (n_31), .Z (n_40));
  an02d0 g265(.A1 (n_34), .A2 (n_20), .Z (n_39));
  an02d0 g267(.A1 (n_32), .A2 (n_14), .Z (n_38));
  inv0d0 g268(.I (n_35), .ZN (n_37));
  an02d0 g269(.A1 (n_33), .A2 (n_15), .Z (n_36));
  an02d0 g270(.A1 (n_30), .A2 (n_7), .Z (n_35));
  an02d0 g266(.A1 (n_23), .A2 (n_8), .Z (n_34));
  inv0d0 g272(.I (n_29), .ZN (n_33));
  inv0d0 g273(.I (n_27), .ZN (n_32));
  inv0d0 g277(.I (n_25), .ZN (n_31));
  inv0d0 g271(.I (n_19), .ZN (n_30));
  an02d0 g275(.A1 (n_26), .A2 (n_28), .Z (n_29));
  an02d0 g276(.A1 (n_26), .A2 (idat[2]), .Z (n_27));
  an02d0 g280(.A1 (n_10), .A2 (n_28), .Z (n_25));
  inv0d0 g279(.I (n_16), .ZN (n_24));
  inv0d0 g278(.I (n_18), .ZN (n_23));
  inv0d0 g284(.I (n_21), .ZN (n_22));
  an02d0 g287(.A1 (n_4), .A2 (n_11), .Z (n_21));
  inv0d0 g283(.I (n_13), .ZN (n_20));
  an02d0 g274(.A1 (n_17), .A2 (n_2), .Z (n_19));
  an02d0 g281(.A1 (n_17), .A2 (n_9), .Z (n_18));
  an02d0 g282(.A1 (n_17), .A2 (idat[1]), .Z (n_16));
  inv0d0 g285(.I (n_12), .ZN (n_15));
  inv0d0 g293(.I (n_6), .ZN (n_14));
  an02d0 g286(.A1 (n_3), .A2 (n_0), .Z (n_13));
  an02d0 g288(.A1 (n_11), .A2 (n_1), .Z (n_12));
  an02d0 g289(.A1 (n_9), .A2 (idat[2]), .Z (n_10));
  inv0d0 g292(.I (n_5), .ZN (n_8));
  xr02d1 g290(.A1 (n_7), .A2 (idat[0]), .Z (n_26));
  an02d0 g296(.A1 (n_11), .A2 (idat[0]), .Z (n_6));
  xr02d1 g291(.A1 (idat[3]), .A2 (idat[2]), .Z (n_17));
  an02d0 g294(.A1 (n_28), .A2 (n_7), .Z (n_5));
  an02d0 g295(.A1 (n_3), .A2 (idat[1]), .Z (n_4));
  inv0d0 g297(.I (n_1), .ZN (n_2));
  an02d0 g298(.A1 (idat[3]), .A2 (idat[2]), .Z (n_0));
  an02d0 g299(.A1 (idat[3]), .A2 (idat[0]), .Z (n_1));
  an02d0 g300(.A1 (idat[1]), .A2 (idat[0]), .Z (n_9));
  inv0d0 g303(.I (idat[0]), .ZN (n_3));
  inv0d0 g304(.I (idat[3]), .ZN (n_28));
  inv0d0 g301(.I (idat[2]), .ZN (n_11));
  inv0d0 g302(.I (idat[1]), .ZN (n_7));
endmodule

