
// Generated by Cadence Genus(TM) Synthesis Solution 17.24-s038_1
// Generated on: Jul 23 2023 13:24:58 IST (Jul 23 2023 07:54:58 UTC)

// Verification Directory fv/present_sbox 

module present_sbox(op, idat, key);
  input [3:0] idat, key;
  output [3:0] op;
  wire [3:0] idat, key;
  wire [3:0] op;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_13, n_14, n_15, n_16, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_41;
  xr02d1 g257(.A1 (n_28), .A2 (key[3]), .Z (op[3]));
  xr02d1 g255(.A1 (n_26), .A2 (key[2]), .Z (op[2]));
  xr03d1 g256(.A1 (n_27), .A2 (key[0]), .A3 (idat[3]), .Z (op[0]));
  xr02d1 g258(.A1 (n_24), .A2 (key[1]), .Z (op[1]));
  nd02d0 g260(.A1 (n_25), .A2 (n_16), .ZN (n_28));
  nd02d0 g264(.A1 (n_23), .A2 (n_4), .ZN (n_27));
  nd03d0 g259(.A1 (n_6), .A2 (n_20), .A3 (n_22), .ZN (n_26));
  nr02d0 g262(.A1 (n_21), .A2 (n_10), .ZN (n_25));
  nr03d0 g261(.A1 (n_0), .A2 (n_8), .A3 (n_41), .ZN (n_24));
  nd02d0 g269(.A1 (n_19), .A2 (idat[2]), .ZN (n_23));
  nd02d0 g263(.A1 (n_15), .A2 (n_2), .ZN (n_22));
  nr02d0 g265(.A1 (n_18), .A2 (idat[3]), .ZN (n_21));
  nd03d0 g270(.A1 (idat[2]), .A2 (n_13), .A3 (n_7), .ZN (n_20));
  inv0d0 g271(.I (n_18), .ZN (n_19));
  nd02d0 g267(.A1 (n_14), .A2 (idat[1]), .ZN (n_16));
  nd02d0 g268(.A1 (n_14), .A2 (n_9), .ZN (n_15));
  nr02d0 g273(.A1 (n_13), .A2 (n_1), .ZN (n_18));
  nr02d0 g272(.A1 (n_9), .A2 (idat[2]), .ZN (n_10));
  nr03d0 g275(.A1 (idat[0]), .A2 (n_5), .A3 (n_7), .ZN (n_8));
  nd03d0 g276(.A1 (idat[1]), .A2 (n_3), .A3 (n_5), .ZN (n_6));
  xr02d1 g277(.A1 (idat[3]), .A2 (idat[2]), .Z (n_14));
  nd02d0 g281(.A1 (n_5), .A2 (idat[0]), .ZN (n_4));
  nr02d0 g283(.A1 (n_3), .A2 (n_2), .ZN (n_13));
  nr02d0 g278(.A1 (idat[1]), .A2 (idat[0]), .ZN (n_1));
  nr02d0 g279(.A1 (idat[3]), .A2 (idat[1]), .ZN (n_0));
  nd02d0 g282(.A1 (idat[3]), .A2 (idat[0]), .ZN (n_9));
  inv0d0 g285(.I (idat[0]), .ZN (n_3));
  inv0d0 g284(.I (idat[1]), .ZN (n_2));
  inv0d0 g286(.I (idat[3]), .ZN (n_7));
  inv0d0 g287(.I (idat[2]), .ZN (n_5));
  an02d0 g2(.A1 (n_14), .A2 (n_13), .Z (n_41));
endmodule

