
// Generated by Cadence Genus(TM) Synthesis Solution 17.24-s038_1
// Generated on: Jul 21 2023 20:11:40 IST (Jul 21 2023 14:41:40 UTC)

// Verification Directory fv/psi 

module psi(all_input, all_output);
  input [39:0] all_input;
  output [9:0] all_output;
  wire [39:0] all_input;
  wire [9:0] all_output;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9;
  an03d0 g227(.A1 (n_6), .A2 (all_input[17]), .A3 (all_input[7]), .Z
       (all_output[7]));
  an03d0 g222(.A1 (n_1), .A2 (all_input[18]), .A3 (all_input[8]), .Z
       (all_output[8]));
  an03d0 g223(.A1 (n_7), .A2 (all_input[19]), .A3 (all_input[9]), .Z
       (all_output[9]));
  an03d0 g225(.A1 (n_4), .A2 (all_input[16]), .A3 (all_input[6]), .Z
       (all_output[6]));
  an03d0 g229(.A1 (n_5), .A2 (all_input[15]), .A3 (all_input[5]), .Z
       (all_output[5]));
  an03d0 g226(.A1 (n_3), .A2 (all_input[12]), .A3 (all_input[2]), .Z
       (all_output[2]));
  an03d0 g228(.A1 (n_0), .A2 (all_input[13]), .A3 (all_input[3]), .Z
       (all_output[3]));
  an03d0 g221(.A1 (n_9), .A2 (all_input[14]), .A3 (all_input[4]), .Z
       (all_output[4]));
  an03d0 g230(.A1 (n_8), .A2 (all_input[11]), .A3 (all_input[1]), .Z
       (all_output[1]));
  an03d0 g224(.A1 (n_2), .A2 (all_input[10]), .A3 (all_input[0]), .Z
       (all_output[0]));
  an02d0 g235(.A1 (all_input[34]), .A2 (all_input[24]), .Z (n_9));
  an02d0 g239(.A1 (all_input[31]), .A2 (all_input[21]), .Z (n_8));
  an02d0 g231(.A1 (all_input[39]), .A2 (all_input[29]), .Z (n_7));
  an02d0 g233(.A1 (all_input[37]), .A2 (all_input[27]), .Z (n_6));
  an02d0 g240(.A1 (all_input[35]), .A2 (all_input[25]), .Z (n_5));
  an02d0 g237(.A1 (all_input[36]), .A2 (all_input[26]), .Z (n_4));
  an02d0 g236(.A1 (all_input[32]), .A2 (all_input[22]), .Z (n_3));
  an02d0 g232(.A1 (all_input[30]), .A2 (all_input[20]), .Z (n_2));
  an02d0 g234(.A1 (all_input[38]), .A2 (all_input[28]), .Z (n_1));
  an02d0 g238(.A1 (all_input[33]), .A2 (all_input[23]), .Z (n_0));
endmodule

