
// Generated by Cadence Genus(TM) Synthesis Solution 17.24-s038_1
// Generated on: Jul 21 2023 20:23:38 IST (Jul 21 2023 14:53:38 UTC)

// Verification Directory fv/psi 

module psi(all_input, all_output);
  input [39:0] all_input;
  output [9:0] all_output;
  wire [39:0] all_input;
  wire [9:0] all_output;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19;
  nr02d0 g230(.A1 (n_15), .A2 (n_11), .ZN (all_output[1]));
  nr02d0 g226(.A1 (n_1), .A2 (n_0), .ZN (all_output[2]));
  nr02d0 g223(.A1 (n_16), .A2 (n_12), .ZN (all_output[9]));
  nr02d0 g224(.A1 (n_14), .A2 (n_6), .ZN (all_output[0]));
  nr02d0 g222(.A1 (n_8), .A2 (n_18), .ZN (all_output[8]));
  nr02d0 g229(.A1 (n_13), .A2 (n_10), .ZN (all_output[5]));
  nr02d0 g225(.A1 (n_7), .A2 (n_3), .ZN (all_output[6]));
  nr02d0 g227(.A1 (n_19), .A2 (n_2), .ZN (all_output[7]));
  nr02d0 g221(.A1 (n_4), .A2 (n_17), .ZN (all_output[4]));
  nr02d0 g228(.A1 (n_9), .A2 (n_5), .ZN (all_output[3]));
  nd02d0 g231(.A1 (all_input[37]), .A2 (all_input[27]), .ZN (n_19));
  nd02d0 g247(.A1 (all_input[18]), .A2 (all_input[8]), .ZN (n_18));
  nd02d0 g239(.A1 (all_input[14]), .A2 (all_input[4]), .ZN (n_17));
  nd02d0 g235(.A1 (all_input[39]), .A2 (all_input[29]), .ZN (n_16));
  nd02d0 g248(.A1 (all_input[31]), .A2 (all_input[21]), .ZN (n_15));
  nd02d0 g233(.A1 (all_input[30]), .A2 (all_input[20]), .ZN (n_14));
  nd02d0 g249(.A1 (all_input[35]), .A2 (all_input[25]), .ZN (n_13));
  nd02d0 g240(.A1 (all_input[19]), .A2 (all_input[9]), .ZN (n_12));
  nd02d0 g250(.A1 (all_input[11]), .A2 (all_input[1]), .ZN (n_11));
  nd02d0 g232(.A1 (all_input[15]), .A2 (all_input[5]), .ZN (n_10));
  nd02d0 g241(.A1 (all_input[33]), .A2 (all_input[23]), .ZN (n_9));
  nd02d0 g236(.A1 (all_input[38]), .A2 (all_input[28]), .ZN (n_8));
  nd02d0 g242(.A1 (all_input[36]), .A2 (all_input[26]), .ZN (n_7));
  nd02d0 g234(.A1 (all_input[10]), .A2 (all_input[0]), .ZN (n_6));
  nd02d0 g243(.A1 (all_input[13]), .A2 (all_input[3]), .ZN (n_5));
  nd02d0 g237(.A1 (all_input[34]), .A2 (all_input[24]), .ZN (n_4));
  nd02d0 g244(.A1 (all_input[16]), .A2 (all_input[6]), .ZN (n_3));
  nd02d0 g238(.A1 (all_input[17]), .A2 (all_input[7]), .ZN (n_2));
  nd02d0 g245(.A1 (all_input[32]), .A2 (all_input[22]), .ZN (n_1));
  nd02d0 g246(.A1 (all_input[12]), .A2 (all_input[2]), .ZN (n_0));
endmodule

