
// Generated by Cadence Genus(TM) Synthesis Solution 17.24-s038_1
// Generated on: Jul 21 2023 20:22:03 IST (Jul 21 2023 14:52:03 UTC)

// Verification Directory fv/psi 

module psi(all_input, all_output);
  input [39:0] all_input;
  output [9:0] all_output;
  wire [39:0] all_input;
  wire [9:0] all_output;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19;
  an02d0 g230(.A1 (n_11), .A2 (n_15), .Z (all_output[1]));
  an02d0 g226(.A1 (n_0), .A2 (n_1), .Z (all_output[2]));
  an02d0 g223(.A1 (n_12), .A2 (n_16), .Z (all_output[9]));
  an02d0 g224(.A1 (n_6), .A2 (n_14), .Z (all_output[0]));
  an02d0 g222(.A1 (n_18), .A2 (n_8), .Z (all_output[8]));
  an02d0 g229(.A1 (n_10), .A2 (n_13), .Z (all_output[5]));
  an02d0 g225(.A1 (n_3), .A2 (n_7), .Z (all_output[6]));
  an02d0 g227(.A1 (n_2), .A2 (n_19), .Z (all_output[7]));
  an02d0 g221(.A1 (n_17), .A2 (n_4), .Z (all_output[4]));
  an02d0 g228(.A1 (n_5), .A2 (n_9), .Z (all_output[3]));
  an02d0 g231(.A1 (all_input[37]), .A2 (all_input[27]), .Z (n_19));
  an02d0 g247(.A1 (all_input[18]), .A2 (all_input[8]), .Z (n_18));
  an02d0 g239(.A1 (all_input[14]), .A2 (all_input[4]), .Z (n_17));
  an02d0 g235(.A1 (all_input[39]), .A2 (all_input[29]), .Z (n_16));
  an02d0 g248(.A1 (all_input[31]), .A2 (all_input[21]), .Z (n_15));
  an02d0 g233(.A1 (all_input[30]), .A2 (all_input[20]), .Z (n_14));
  an02d0 g249(.A1 (all_input[35]), .A2 (all_input[25]), .Z (n_13));
  an02d0 g240(.A1 (all_input[19]), .A2 (all_input[9]), .Z (n_12));
  an02d0 g250(.A1 (all_input[11]), .A2 (all_input[1]), .Z (n_11));
  an02d0 g232(.A1 (all_input[15]), .A2 (all_input[5]), .Z (n_10));
  an02d0 g241(.A1 (all_input[33]), .A2 (all_input[23]), .Z (n_9));
  an02d0 g236(.A1 (all_input[38]), .A2 (all_input[28]), .Z (n_8));
  an02d0 g242(.A1 (all_input[36]), .A2 (all_input[26]), .Z (n_7));
  an02d0 g234(.A1 (all_input[10]), .A2 (all_input[0]), .Z (n_6));
  an02d0 g243(.A1 (all_input[13]), .A2 (all_input[3]), .Z (n_5));
  an02d0 g237(.A1 (all_input[34]), .A2 (all_input[24]), .Z (n_4));
  an02d0 g244(.A1 (all_input[16]), .A2 (all_input[6]), .Z (n_3));
  an02d0 g238(.A1 (all_input[17]), .A2 (all_input[7]), .Z (n_2));
  an02d0 g245(.A1 (all_input[32]), .A2 (all_input[22]), .Z (n_1));
  an02d0 g246(.A1 (all_input[12]), .A2 (all_input[2]), .Z (n_0));
endmodule

