
// Generated by Cadence Genus(TM) Synthesis Solution 17.24-s038_1
// Generated on: Jul 29 2023 16:14:08 IST (Jul 29 2023 10:44:08 UTC)

// Verification Directory fv/relu 

module relu(x, y);
  input [7:0] x;
  output [7:0] y;
  wire [7:0] x;
  wire [7:0] y;
  wire n_5;
  assign y[7] = 1'b0;
  an02d0 g147(.A1 (n_5), .A2 (x[6]), .Z (y[6]));
  an02d0 g153(.A1 (n_5), .A2 (x[0]), .Z (y[0]));
  an02d0 g148(.A1 (n_5), .A2 (x[5]), .Z (y[5]));
  an02d0 g152(.A1 (n_5), .A2 (x[2]), .Z (y[2]));
  an02d0 g149(.A1 (n_5), .A2 (x[3]), .Z (y[3]));
  an02d0 g151(.A1 (n_5), .A2 (x[4]), .Z (y[4]));
  an02d0 g150(.A1 (n_5), .A2 (x[1]), .Z (y[1]));
  inv0d0 g154(.I (x[7]), .ZN (n_5));
endmodule

